In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model, svm
from sklearn import metrics

In [2]:
data = pd.read_csv('wifi_localization.txt', sep='\t',  names = ["Room 1", "Room 2", "Room 3", "Room 4", "Room 5", "Room 6", "Room 7", "wifi N"])

Переносим файл исходных данных в df

In [12]:
data

Room 1  Room 2  Room 3  Room 4  Room 5  Room 6  Room 7  wifi N
0        -64     -56     -61     -66     -71     -82     -81       1
1        -68     -57     -61     -65     -71     -85     -85       1
2        -63     -60     -60     -67     -76     -85     -84       1
3        -61     -60     -68     -62     -77     -90     -80       1
4        -63     -65     -60     -63     -77     -81     -87       1
5        -64     -55     -63     -66     -76     -88     -83       1
6        -65     -61     -65     -67     -69     -87     -84       1
7        -61     -63     -58     -66     -74     -87     -82       1
8        -65     -60     -59     -63     -76     -86     -82       1
9        -62     -60     -66     -68     -80     -86     -91       1
10       -67     -61     -62     -67     -77     -83     -91       1
11       -65     -59     -61     -67     -72     -86     -81       1
12       -63     -57     -61     -65     -73     -84     -84       1
13       -66     -60     -65     -62     -70     -85     -83       1
14       -61     -59     -65     -63     -74     -89     -87       1
15       -67     -60     -59     -61     -71     -86     -91       1
16       -63     -56     -60     -62     -70     -84     -91       1
17       -60     -54     -59     -65     -73     -83     -84       1
18       -60     -58     -60     -61     -73     -84     -88       1
19       -62     -59     -63     -64     -70     -84     -84       1
20       -63     -59     -64     -66     -72     -84     -90       1
21       -65     -59     -66     -65     -68     -82     -85       1
22       -63     -56     -63     -65     -72     -82     -89       1
23       -67     -60     -66     -65     -75     -86     -87       1
24       -63     -57     -67     -66     -79     -86     -89       1
25       -66     -59     -64     -68     -68     -97     -83       1
26       -65     -61     -64     -68     -77     -86     -89       1
27       -66     -57     -65     -69     -78     -85     -85       1
28       -67     -57     -64     -71     -75     -89     -87       1
29       -65     -62     -62     -65     -77     -84     -85       1
...      ...     ...     ...     ...     ...     ...     ...     ...
1970     -58     -55     -50     -54     -48     -80     -86       4
1971     -61     -51     -52     -56     -47     -86     -90       4
1972     -60     -52     -51     -55     -48     -86     -90       4
1973     -63     -61     -49     -58     -46     -92     -83       4
1974     -61     -54     -45     -54     -43     -88     -80       4
1975     -57     -53     -45     -54     -52     -84     -82       4
1976     -56     -60     -47     -58     -46     -80     -82       4
1977     -55     -57     -43     -59     -53     -81     -85       4
1978     -55     -54     -43     -60     -51     -84     -88       4
1979     -56     -55     -45     -59     -52     -84     -86       4
1980     -55     -54     -46     -60     -50     -84     -86       4
1981     -56     -54     -47     -59     -52     -84     -91       4
1982     -56     -55     -44     -61     -51     -84     -87       4
1983     -57     -55     -48     -59     -51     -81     -86       4
1984     -59     -54     -49     -58     -52     -83     -93       4
1985     -58     -53     -46     -59     -50     -86     -90       4
1986     -56     -55     -44     -60     -51     -84     -86       4
1987     -56     -53     -43     -61     -58     -80     -85       4
1988     -57     -55     -50     -57     -49     -84     -85       4
1989     -56     -55     -54     -61     -46     -79     -79       4
1990     -57     -54     -49     -61     -43     -79     -85       4
1991     -59     -53     -45     -57     -45     -81     -82       4
1992     -57     -56     -53     -62     -48     -87     -88       4
1993     -63     -55     -50     -63     -50     -91     -85       4
1994     -61     -54     -51     -63     -44     -87     -88       4
1995     -59     -59     -48     -66     -50     -86     -94       4
1996

Проверям правильно ли данные преобразовались

In [4]:
X = data.iloc[:,[0,1,2,3,4,5,6]]
Y = data.iloc[:,[7]]

Разделям исходный df на два, первый хранит замеры в комнатах, второй номера вайфай точек соответствующих сигналам первой таблицы

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, shuffle=True, stratify=Y)

Перемешиваем данные и разделяем их на тренировочные и тестовые

In [7]:
log_r = linear_model.LogisticRegression(verbose=1)
log_r.fit(X_train, Y_train)

[LibLinear]

/home/snowpc/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=1, warm_start=False)

Тренируем модель

In [8]:
Y_pred = log_r.predict(X_test)
print(Y_pred)
print(Y_test)

[1 1 4 4 3 1 4 4 2 2 2 2 1 1 1 3 2 3 2 2 3 4 4 4 4 1 1 1 2 2 1 3 3 1 3 4 1
 1 4 2 4 1 4 2 4 3 1 3 4 3 2 1 3 1 3 4 2 3 4 2 2 4 1 1 2 2 1 4 4 3 2 3 3 4
 1 4 4 2 1 3 4 2 1 4 3 3 2 3 4 3 3 1 2 4 4 1 2 2 2 3 2 4 3 3 1 2 3 3 3 4 1
 2 4 2 1 3 3 1 4 4 4 2 3 2 4 3 3 3 2 4 2 3 1 2 2 3 2 3 3 4 3 2 2 3 3 1 1 3
 2 3 4 3 2 4 4 3 4 1 1 1 4 1 1 2 1 2 4 2 3 4 1 2 3 4 1 3 3 2 3 2 4 3 4 2 3
 4 1 1 4 2 4 4 4 1 3 3 2 3 2 2 2 4 4 1 1 1 2 1 2 2 3 2 4 4 2 1 4 1 1 2 2 3
 3 1 2 3 4 4 4 3 1 4 1 2 4 1 4 1 1 4 2 4 3 1 1 2 1 3 2 3 4 1 4 3 4 1 4 1 4
 4 2 2 2 4 3 1 4 1 2 2 1 3 1 1 1 4 3 4 4 2 4 4 4 2 3 1 3 2 1 4 1 2 3 3 2 3
 4 4 2 2 1 2 2 4 2 2 2 2 1 4 4 4 3 3 3 4 1 2 2 1 4 1 3 2 1 3 1 2 4 3 3 3 1
 1 1 1 4 1 3 2 1 4 2 4 4 1 4 1 2 3 1 2 4 2 1 1 4 2 3 3 2 2 4 3 3 4 2 4 4 2
 3 3 2 1 3 1 4 3 2 1 3 2 1 3 1 2 2 3 3 1 1 2 1 2 1 4 1 1 2 3]
      wifi N
407        1
341        1
1734       4
1758       4
1210       3
150        1
1920       4
1679       4
749        2
645        2
924        2
678        2
439        1
402   

Тестируем и смотрим точность полученной модели 

In [9]:
print(metrics.accuracy_score(Y_test, Y_pred))

0.9775


In [10]:
print(metrics.classification_report(Y_test, Y_pred))

             precision    recall  f1-score   support

          1       1.00      1.00      1.00       100
          2       0.94      0.98      0.96       100
          3       0.98      0.93      0.95       100
          4       0.99      1.00      1.00       100

avg / total       0.98      0.98      0.98       400



In [11]:
print(metrics.confusion_matrix(Y_test, Y_pred))

[[100   0   0   0]
 [  0  98   2   0]
 [  0   6  93   1]
 [  0   0   0 100]]
